### ISSUE TITLE
sc-eslint and gulp-strip-react-dom-comment should be devDependencies

### ISSUE THREAD

**Issue by acrispino** [StoneCypher/flocks.js#23]
sc-eslint and gulp-strip-react-dom-comment  don't seem to be necessary to actually run flocks.

This would allow npm users to not install sc-eslint, gulp-strip-react-dom-comment, and their dependencies to use flocks. This probably affects me more than others because I prefer to vendor my node_modules.

Related, I feel that react should be a dependency or peerDependency.

**Comment by StoneCypher** [comment]
I will look into this.  I am relatively new to the NPM world.  Thank you for the advice.

**Comment by StoneCypher** [comment]
All three pieces of advice taken.

Went with a dep instead of a peer dep for the sake of making testing not a pain in the rear
