### ISSUE TITLE
Can't initialize in Chrome

### ISSUE THREAD

**Issue by acrispino** [StoneCypher/flocks.js#24]
Here's some example code: https://github.com/acrispino/flockstest

Everything works as expected in Firefox. On Chrome, the calling Flocks.create fails:

```
flocks.jsx:69 Flocks2 [1] Flocks2 root creation begins
flocks.jsx:69 Flocks2 [2]  - Flocks2 engaging auto-context
flocks.jsx:143 Uncaught TypeError: Converting circular structure to JSON
```

The issue seems to be that the flocks context contains a copy of the config object, which contains a reference to the target element for the root component. In Chrome, this causes the call to JSON.stringify to fail.

Firefox and IE9+ seem to serialize elements as objects without any of the DOM properties. IE8 returns undefined.

**Comment by StoneCypher** [comment]
Oh hell, I thought I took that stringify out already.  That was temporary.

Thanks for the catch.  Will fix tonight after work :smile: 

I need to set up non-trivial testing too

**Comment by StoneCypher** [comment]
Yesterday got long.  

Notes for myself tonight: you want http://oranlooney.com/deep-copy-javascript/ or https://github.com/pvorb/node-clone or http://stackoverflow.com/a/12941013/763127 .
